appeal/urls.py
from django.urls import path

from appeal.views import submit_appeal

from appeal.views import AppealDetailView

app_name = 'appeal'

urlpatterns = [
    path('', submit_appeal, name='appeals'),
    path('view/<slug:uid>', AppealDetailView.as_view(), name='view')
]

cofe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('site_cofe.urls', namespace='info')),
    path('tapls/', include('tapls.urls', namespace='news')),
    path('appeal/', include('appeal.urls', namespace='appeal')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

site_cofe/urls.py
from django.urls import path

from site_cofe.views import SiteListView

app_name = "site_cofe"

urlpatterns = [
    path('main/', SiteListView.as_view(), name="main")
]

tapls/urls.py
from django.urls import path
from django.views.generic import DetailView

from tapls.views import NewsListView

from tapls.models import Tapls

from tapls.views import tapls_detail_view


app_name = 'tapls'

urlpatterns = [
    path('', NewsListView.as_view(), name='tapls_list'),
    path('tapls/<int:pk>/', tapls_detail_view, name='details'),
]

appeal/models.py
from django.contrib.auth.models import User
from django.db import models


class Appeal(models.Model):
    TYPES = (
        ('Культура', 'Культура'),
        ('Лунная терраса', 'Лунная терраса'),
        ('8 марта', '8 марта'),
        ('Дубовый', 'Дубовый'),
        ('Тайный сад', 'Тайный сад'),
        ('Два романтика', 'Два романтика'),
    )

    STATUS_CHOICE = (("a", "В обработке"),
                     ("b", "Выполнено"),
                     ("c", "Отклонено"))

    type = models.CharField(choices=TYPES, max_length=128, verbose_name='Стол')
    сapacity = models.CharField(max_length=60, verbose_name='Количество человек')
    contact = models.CharField(max_length=128, verbose_name='Контактая информация')
    email = models.EmailField("Электронная почта", blank=False)
    status = models.CharField(max_length=100, verbose_name='Статус', choices=STATUS_CHOICE)
    uid = models.CharField(max_length=64, blank=False, null=False, db_index=True, unique=True)
    date = models.DateTimeField("Дата отправки", auto_now_add=True)

    def __iter__(self):
        for field in self._meta.fields:
            yield field.verbose_name, field.value_to_string(self)

    class Meta:
        verbose_name = 'Обращение'
        verbose_name_plural = 'Обращения'
        #ordering = ('-date', )


class Answer(models.Model):
    text = models.TextField(blank=False)
    file = models.FileField(upload_to='answer/%Y/%m/%d', blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    send_date = models.DateTimeField('Дата отправки', auto_now_add=True)
    update_date = models.DateTimeField('Дата редактирования', auto_now=True)
    appeal = models.OneToOneField(Appeal, on_delete=models.CASCADE, related_name='answer', verbose_name='Заявка')

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'
        ordering = ('-send_date', '-update_date')

comment/models.py
from django.db import models


class Comment(models.Model):
    text = models.TextField(blank=False, verbose_name="Текст комментария")
    date_of_create = models.DateTimeField(auto_now_add=True, verbose_name="Дата отправления")

    def __str__(self):
        return self.text[:32] + '...'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-date_of_create',)

site_cofe/models.py
from django.db import models


class Site(models.Model):
    name = models.CharField(max_length=128, verbose_name='Название кофе')
    description = models.TextField(verbose_name='Описание кофе')
    image = models.ImageField(upload_to='%Y/%m/%d', blank=True, null=True)

    class Meta:
        verbose_name = 'Кофе'
        verbose_name_plural = 'Кофе'

tapls/models.py
from django.db import models


class Tapls(models.Model):
    title = models.CharField(max_length=128, verbose_name='Название')
    сapacity = models.CharField(max_length=60, verbose_name='Вместимость')
    price = models.CharField(max_length=60, verbose_name='Стоимость')
    publish_date = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')
    edit_date = models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата редактирования')
    image = models.ImageField(upload_to='%Y/%m/%d', blank=True, null=True)
    view = models.CharField(max_length=128, verbose_name='Просмотры')

    class Meta:
        verbose_name = 'Стол'
        verbose_name_plural = 'Столы'
        ordering = ('-publish_date', '-edit_date')

appeal/forms.py
from django import forms

from appeal.models import Appeal


class AppealForm(forms.ModelForm):
    class Meta:
        model = Appeal
        exclude = ['id', 'uid', 'status']

comment/forms.py
from django import forms

from comment.models import Comment


class CommentForm(forms.Form):
    name = forms.CharField(max_length=128, label='Имя')
    text = forms.CharField(widget=forms.Textarea, label='Комментарий')

appeal/views.py
import hashlib
from datetime import datetime

from django.core.mail import send_mail
from django.shortcuts import render, redirect

from appeal.forms import AppealForm
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.html import strip_tags
from django.views.generic import DetailView

from appeal.models import Appeal


def submit_appeal(request):
    if request.method == 'POST':
        form = AppealForm(request.POST, request.FILES)
        if form.is_valid():
            appeal = form.save(commit=False)

            while True:
                uid = appeal.contact + appeal.type + appeal.сapacity + str(datetime.now().timestamp())
                m = hashlib.sha256()
                m.update(bytes(uid, encoding='utf-8'))
                uid = m.hexdigest()

                if  len(Appeal.objects.filter(uid=uid)) == 0:
                    break

            appeal.uid = uid

            appeal.save()

            html_message = render_to_string('message/notification_message.html', context={'type': appeal.type,
                                                                                           'url': request.build_absolute_uri(f'/appeal/view/{uid}')})
            message = strip_tags(html_message)
            send_mail(subject=f'Обращение №{appeal.id}',
                      message=message,
                      html_message=html_message,
                      from_email='admin@sity.ru',
                      recipient_list=[appeal.email])
            return redirect(reverse('appeal:appeals'))
    else:
        form = AppealForm()
    return render(request, 'appeal/appeal.html', {'form': form})


class AppealDetailView(DetailView):
    model = Appeal
    template_name = 'appeal/appeal_detail.html'
    context_object_name = 'appeal'
    slug_field = 'uid'
    slug_url_kwarg = 'uid'

comment/views.py
from django.shortcuts import render

# Create your views here.

site_cofe/views.py
from django.shortcuts import render
from django.views.generic import ListView

from site_cofe.models import Site


class SiteListView(ListView):
    model = Site
    context_object_name = 'sity'
    template_name = 'main.html'

tapls/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView
from tapls.models import Tapls

from comment.forms import CommentForm

from comment.models import Comment


class NewsListView(ListView):
    model = Tapls
    template_name = 'tapls/tepls_list.html'
    context_object_name = 'tapls_list'


def tapls_detail_view(request, pk):
    object_list = Tapls.objects.filter(pk=pk)
    pk = get_object_or_404(Tapls, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            new_comment = Comment(text=text)
            new_comment.save()
            return redirect(reverse('tapls:details', kwargs={'pk': pk.pk}))

    else:
        form = CommentForm()
    return render(request, "tapls/tapls_details.html", {'form': form, 'object_list': object_list, 'pk': pk})

appeal/templates/appeal/appeal.html
{% extends 'root.html' %}
{% block content %}

<form method="post" class="mt-5 ms-5" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Отравить</button>
</form>

{% endblock %}

appeal/templates/appeal/appeal_detail.html
{% extends 'root.html'%}
{% block content %}
<div class="ms-3 mt-3">
  <h1>Обращение #{{ appeal.id }}</h1>
  <p>ФИО: {{ appeal.contact }}</p>
  <p>Электронная почта: {{ appeal.email }}</p>
  <p>Тип заявки: {{ appeal.get_type_display }}</p>
  <p>Статус заявки: {{ appeal.get_status_display }}</p>
  {% if appeal.file %}
    <p><a href="{{ appeal.file.url }}">Файл</a></p>
  {% endif %}
  <p>Дата отправки: {{ appeal.date|date:'d.m.Y' }}</p>
  {% if appeal.answer %}
    <div>
      <h2>Ответ на обращение #{{ appeal.id }}</h2>
      {% with appeal.answer as answer %}
      <p>{{ answer.text }}</p>
      <p>Автор: {{ answer.author.get_full_name }}</p>
      <p>Дата отправки: {{ answer.send_date|date:'d.m.Y' }}</p>
      {% if send_date != update_date %}
        <p>Дата изменения: {{ answer.update_date }}</p>
      {% endif %}
      {% endwith %}
    </div>
  {% else %}
  <div>
    <h2>Ожидайте ответ на ваше обращение!</h2>
  </div>
  {% endif %}
</div>
{% endblock %}

appeal/templates/message/notification_message.html
<!DOCTYPE html>
<html lang="en">
<body>
<p>Вы успешно оставили заявку на сайте Sity.ru.</p>
<p>Тип заявки: <i>{{ type }}</i></p>
<p>Статус заявки вы можете узнать по адресу: <a href="{{ url }}">{{ url }}</a></p>
</body>
</html>

site_cofe/templates/main.html
{% extends "root.html" %}
{% block content %}
<div class="content d-flex flex-column align-items-center">
    {% for sity in sity %}
        <h1 class="text-center mt-5">{{ sity.name }}</h1>
        <p class="text-center m-5">{{ sity.description }}</p>
        <img src={{ sity.image.url }} alt="...">
    {% endfor %}
    <script src="//code.jivo.ru/widget/b0DsvZEPVu" async></script>
</div>

{% endblock %}

tapls/templates/tapls/tapls_details.html
{% extends 'root.html' %}
{% block content %}
<div class="news mt-4 ms-5">
        <h3>{{ pk.title }}</h3>
            <img src="{{ pk.image.url }}" alt="" class="w-25">
        <p class="mt-3">{{ pk.text }}</p>
    </div>
<form method="post">
    {% csrf_token %}
        {{ form.as_p }}
       <!-- <div class="form-group d-flex justify-content-between align-items-center" style="width: 25rem;">
            <input type="text" value="{{ author }}" placeholder="Ваше имя">
            <input type="text" value="{{ text }}" placeholder="Ваш комментарий">
        </div>!-->
        <button type="submit" class="btn btn-secondary mt-3" style="background-color: #1A5686;">Отправить</button>

    </form>
{% endblock %}

tapls/templates/tapls/tepls_list.html
{% extends 'root.html' %}
{% block content %}
<h1 class="text-center mt-3">Столы</h1>
<div class="row row-cols-3 row-cols-md-6 g-6">
{% for tapls in tapls_list %}
<div class="d-flex m-5">
<div class="card" style="width: 18rem;">
  <img src="{{ tapls.image.url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Стол "{{ tapls.title }}"</h5>
    <p class="card-text">Вместимость: {{ tapls.сapacity }}</p>
      <p class="card-text">Стоимость: от {{ tapls.price }}руб/чел.</p>
    <a href="{% url 'tapls:details' tapls.id %}" class="btn btn" style="background-color: #FFE4B5;">Подробнее</a>
  </div>
</div>
</div>

{% endfor %}
</div>
{% endblock %}

templates/root.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-dark" style="background-color: #FFE4B5;">
  <div class="container-fluid">
    <a class="navbar-brand text-dark" href="{% url 'info:main' %}">Уютное кафе</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active text-dark" aria-current="page" href="{% url 'info:main' %}">Главная</a>
        <a class="nav-link text-dark" href="{% url 'tapls:tapls_list' %}">Столы</a>
        <a class="nav-link text-dark href="{% url 'appeal:appeals' %}">Забронировать стол</a>
      </div>
    </div>
  </div>
</nav>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>